"""Item 18 acceptance: LIC-329505 = 324E001 steam-side condensate level ("controlled steam trap").
LV-329505 drains the shell condensate generated by Q_e001/lambda_steam.  Steam-side only ->
conservation-neutral on the urea/water network: at design gen == drain, level == SP, no drift.
Red before edit (LIC_329505 / LI_329505 absent), green after.  Run: cd backend && python ../scratchpad/probe_lic9505.py
"""
import sys, os
BACKEND = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "backend")
sys.path.insert(0, BACKEND); os.chdir(BACKEND)
import main

telem = main.step_sim(0.1)                                   # tick 1 = design point
e001  = telem["EVAP_324"]["E001"]
lic   = e001["LIC_329505"]
lvl   = e001["LI_329505"]
cond  = e001["cond_kgh"]
sp    = main.R324_E001_COND_LVL_SP
cdes  = main.R324_E001_COND_DES

print(f"R324_E001_Q_DES_KW    = {main.R324_E001_Q_DES_KW:.1f} kW")
print(f"R324_E001_COND_DES    = {cdes:.1f} kg/h  (steam condensed at design)")
print(f"LI_329505 (level)     = {lvl} %   (SP {sp})")
print(f"LIC_329505.pv/op/mode = {lic['pv']} / {lic['op']} / {lic['mode']}")
print(f"cond_kgh (live gen)   = {cond} kg/h")

# --- drift check: run 400 s, level must hold at SP (gen == drain at design) -------
for _ in range(4000):
    telem = main.step_sim(0.1)
lvl2 = telem["EVAP_324"]["E001"]["LI_329505"]
print(f"LI_329505 after 400 s = {lvl2} %   (must stay ~{sp})")

bad = 0
if cdes <= 0:
    print("FAIL: COND_DES non-positive"); bad += 1
if not (sp-0.2 <= lvl <= sp+0.2):
    print("FAIL: boot level off SP (du!=0 at design)"); bad += 1
if not (49.0 <= lic["op"] <= 51.0):
    print("FAIL: LV-329505 design stroke not ~50%"); bad += 1
if lic["mode"] != "AUTO":
    print("FAIL: LIC-329505 not AUTO"); bad += 1
if not (49.0 <= lvl2 <= 51.0):
    print("FAIL: level drifted off SP over 400 s (gen != drain)"); bad += 1
if not (cond > 0):
    print("FAIL: no live condensate generation"); bad += 1

print(f"\nFAILURES: {bad}")
sys.exit(1 if bad else 0)
